In [2]:
import pandas as pd

In [3]:
amount = pd.Series([20,30,40],name="amount")

data = pd.DataFrame([
    {"category": "food",     "amount": 250,  "city": "Delhi"},
    {"category": "travel",   "amount": 1200, "city": "Mumbai"},
    {"category": "food",     "amount": 90,   "city": "Delhi"},
    {"category": "shopping", "amount": 500,  "city": "Delhi"},
    {"category": "travel",   "amount": 300,  "city": "Mumbai"},
])

data["amount"]                     # column selection
data.loc[1]                          # row by label
data[data["amount"] > 200]        # boolean filter
data.groupby("category")["amount"].sum()

category
food         340
shopping     500
travel      1500
Name: amount, dtype: int64

In [4]:

data["amount"]

0     250
1    1200
2      90
3     500
4     300
Name: amount, dtype: int64

In [5]:
data.loc[1]

category    travel
amount        1200
city        Mumbai
Name: 1, dtype: object

In [6]:
data[data["amount"] > 200]

   category  amount    city
0      food     250   Delhi
1    travel    1200  Mumbai
3  shopping     500   Delhi
4    travel     300  Mumbai

In [7]:
data.groupby("category")["amount"].sum()

category
food         340
shopping     500
travel      1500
Name: amount, dtype: int64

In [8]:
data.iloc[1]

category    travel
amount        1200
city        Mumbai
Name: 1, dtype: object

In [9]:
data.sort_values("amount")

   category  amount    city
2      food      90   Delhi
0      food     250   Delhi
4    travel     300  Mumbai
3  shopping     500   Delhi
1    travel    1200  Mumbai

In [10]:
data

   category  amount    city
0      food     250   Delhi
1    travel    1200  Mumbai
2      food      90   Delhi
3  shopping     500   Delhi
4    travel     300  Mumbai

In [11]:
data = data.sort_values("amount")

In [12]:
data

   category  amount    city
2      food      90   Delhi
0      food     250   Delhi
4    travel     300  Mumbai
3  shopping     500   Delhi
1    travel    1200  Mumbai